version: '3'

services:
  app:
    build:
      context: ./php-app
    volumes:
      - ./php-app:/app
    ports:
      - "3088:80"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./mysql/data:/var/lib/mysql
